# front
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: eduapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: cupofraccoons/eduapp-front:1.5

---
# backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: eduapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: cupofraccoons/eduapp-back:1.5
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              value: jdbc:mysql://database:3306/eduapp_db

---
# database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: eduapp
spec:
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: eduapp_db
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: database-pvc
